---
title: "Untitled"
author: "Ringa"
date: "2021/--/--"
output: html_document
---



```{r}
library(tidytuesdayR)

df <- tt_load("2019-07-02")
```




```{r}
media_franchises <- df$media_franchises
```




```{r}
library(tidyverse)
```





```{r}
library(skimr)

skim(media_franchises)

```





```{r}
media_franchises %>% pull(franchise) %>% length()
```



```{r}
length(unique(media_franchises$franchise))

media_franchises %>% 
  pull(franchise) %>% 
  unique()#%>%
  #length()
```







```{r}
media_franchises %>% 
  count(franchise,sort = T) %>% 
  count(n,sort = T)
```



```{r}
media_franchises %>% 
  count(franchise,sort = T) %>% 
  count(n,sort = T) %>% 
  ggplot(aes(x=n,y=nn))+
  geom_col()
```









```{r}
media_franchises %>% 
  filter(franchise == "Spider-Man")
```



```{r}
media_franchises %>% 
  group_by(franchise) %>% 
  summarise(revenue_sum = sum(revenue)) %>% 
#  mutate(rate = revenue_sum/sum(revenue_sum)) %>% 
#  arrange(desc(rate))
  
  mutate(summarise_franchise = fct_lump(franchise,prop=0.011,w=revenue_sum)) %>% 
  
  filter(summarise_franchise != "Other") %>% 
  
  ggplot(aes(x=fct_reorder(summarise_franchise,revenue_sum), y=revenue_sum))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90))
  
  
  #ggplot(aes(x=fct_reorder(franchise,revenue_sum),y=revenue_sum))+
  #geom_col()+
  #theme(axis.text.x = element_text(angle = 90))
``` 









```{r}
media_franchises %>% 
  count(franchise,year_created) %>% 
  count(franchise,sort = T) %>% 
  filter(n != 1)
```





















```{r}
media_franchises %>% 
  distinct(franchise,year_created) %>% 
  count(franchise) %>% 
  filter(n > 1 )
```









```{r}
media_franchises %>%
  count(franchise, sort = TRUE)


franchises <- media_franchises %>%
  group_by(franchise, original_media, year_created, creators, owners) %>%
  summarize(categories = n(),
            total_revenue = sum(revenue),
            most_profitable = revenue_category[which.max(revenue)]) %>%
  ungroup()




franchises
media_franchises
```



```{r}
franchises %>% 
  count(franchise, sort = T)
```







```{r}
library(glue)

top_franchises <- franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>%
  top_n(20, total_revenue)

top_franchises
```




```{r}
media_franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>% 
 filter(franchise %in% unique(top_franchises$franchise))
```


```{r}
media_franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>%
  semi_join(top_franchises, by = "franchise") 
```





```{r}
media_franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>%
  semi_join(top_franchises, by = "franchise") %>%
  
  mutate(franchise = fct_reorder(franchise, revenue, sum),
         revenue_category = fct_reorder(revenue_category, revenue, sum)) %>%
  
  ggplot(aes(x=franchise, y=revenue)) +
  geom_col(aes(fill = revenue_category)) +
  geom_text(aes(y = total_revenue,
                label = paste0(scales::dollar(total_revenue, accuracy = 1), "B")),
            data = top_franchises,
            hjust = 0) +
  scale_y_continuous(labels = scales::dollar) +
  expand_limits(y = 100) +
  coord_flip() +
  theme(panel.grid.major.y = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "What are the most profitable franchises of all time?",
       fill = "Category",
       x = "",
       y = "Revenue (Billions)")
```

```{r}
media_franchises %>% 
  filter(franchise == "Star Wars")
```




```{r}
media_franchises %>% 
  filter(str_detect(franchise, "Friends"))
```



```{r}

media_franchises %>% 
  group_by(franchise) %>% 
  summarise(sum(revenue)) %>% 
  head(3)

```



```{r}
media_franchises %>%
  group_by(original_media) %>%
  summarize(revenue = sum(revenue)) %>% 
  arrange(desc(revenue)) %>% 
  ggplot(aes(x=fct_reorder(original_media,revenue),y=revenue))+
  geom_col()+
  coord_flip()+
  theme(axis.text.x = element_text(angle = 90))
```





```{r}
media_franchises %>%
  group_by(franchise) %>% 
  add_count(wt=revenue) %>% 
  mutate(new_fran = ifelse(n > 30, franchise, "extra")) %>% 
  
  group_by(original_media,new_fran) %>%
  summarize(revenue = sum(revenue),.groups = "drop") %>% 

  ggplot(aes(fill = new_fran))+
  geom_col(aes(
    x=original_media,
             y=revenue),position = "fill")+
  coord_flip()+
    facet_wrap(~original_media,ncol=3,scales = "free")
  
```




```{r}
media_franchises %>%
  group_by(franchise) %>% 
  add_count(wt=revenue) %>% 
  mutate(new_fran = ifelse(n > 30, franchise, "extra")) %>% 
  
  group_by(original_media,new_fran) %>%
  summarize(revenue = sum(revenue),.groups = "drop") %>% 

  ggplot(aes(fill = new_fran))+
  geom_col(aes(
    x=original_media,
             y=revenue),position = "stack")+
  coord_flip()+
    facet_wrap(~original_media,ncol=3,scales = "free_y")
  
```





```{r}
media_franchises %>%
  group_by(original_media) %>% 
  summarise(n=n(),sum = sum(revenue),.groups = "drop") %>% 
  ggplot(aes(x=fct_reorder(original_media,n),y=n))+
  geom_col()+
  coord_flip()
```




```{r}
media_franchises %>%
  group_by(original_media) %>% 
  summarise(n=n(),sum = sum(revenue),
            mean = sum/n,
            .groups = "drop") %>% 

  ggplot(aes(x=fct_reorder(original_media,mean),y=mean))+
  geom_col()+
  coord_flip()

```







```{r}
media_franchises %>%
  group_by(original_media) %>%
  summarize(revenue = sum(revenue)) %>% 
  arrange(desc(revenue))
```






```{r}
original_media_revenue_categories <- media_franchises %>%
  group_by(original_media) %>%
  filter(sum(revenue) >= 45) %>%
  
  group_by(original_media, revenue_category) %>%
  
  summarize(revenue = sum(revenue)) %>%
  
  ungroup() %>%
  
  mutate(revenue_category = fct_reorder(revenue_category, revenue, sum),
         original_media = fct_reorder(original_media, -revenue, sum))
```


```{r}
original_media_revenue_categories %>%
  
  ggplot(aes(revenue_category, revenue)) +
  geom_col() +
  
  scale_y_continuous(labels = scales::dollar) +
  coord_flip() +
  facet_wrap(~ original_media) +
  
  labs(x = "Revenue category",
       y = "Revenue (Billions)",
       title = "What kinds of media lead to what types of revenue?")
```







```{r}
original_media_revenue_categories %>%
  mutate(revenue_category = fct_rev(revenue_category),
         original_media = fct_rev(original_media)) %>%
 
   ggplot(aes(revenue_category, original_media, fill = revenue)) +
  geom_tile() +

    scale_fill_gradient2(low = "white", high = "red", labels = scales::dollar) +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(fill = "Revenue (billions)")
```










```{r}
unique(media_franchises$revenue_category)
```









































```{r}
unique(media_franchises$original_media)
```




```{r}
media_franchises %>% 
  filter(original_media=="Digital pet")
```






```{r}
media_franchises %>% filter(original_media %in%  c("Comic book","Novel","Book"))
```












```{r}

media_franchises %>% 
  group_by(year_created) %>% 
  summarise(rev_sum=sum(revenue)) %>% 
  ggplot(aes(x=year_created,y=rev_sum))+
  geom_point()
```









```{r}
media_franchises %>% 
  group_by(year_created) %>% 
  summarise(rev_sum=sum(revenue),n=n()) %>%
  mutate(avg = rev_sum / n ) %>% 
  
  ggplot(aes(x=year_created,y=avg))+
  geom_point()
  
```



```{r}
media_franchises %>% 
  filter(year_created == 2000)
```






```{r}
media_franchises %>% 
  group_by(year_created) %>% 
  summarise(rev_sum=sum(revenue),n=n()) %>%
  mutate(average = rev_sum / n ) %>% 
  
  pivot_longer(-year_created,
               names_to = "type",
               values_to = "val") %>% 
  
  ggplot(aes(x=year_created,y=val,color=type))+
  geom_line()


```






```{r}
media_franchises %>% 
  filter(between(year_created,1990,2000 ))
```







```{r}
media_franchises %>% 
  filter(str_detect(owners,
                    c("Capcom","Nintendo","Kodansha","Shueisha",
                      "Toei","Bandai","Sega")
                    )
         )
```









```{r}
media_franchises %>% 
  pull(owners) %>% 
  unique()
```










```{r}
library(tidytext)

media_franchises %>% 
  unnest_tokens(word,owners) %>% 
  count(word,sort = T)
  
```






```{r}
media_franchises %>% 
  unnest_tokens(word,owners) %>% 
  count(word,sort = T) %>% 
  anti_join(stop_words)
```








```{r}
media_franchises %>% 
  mutate(owners = str_to_lower(owners)) %>% 

  mutate(new_owners = case_when(str_detect(owners,"at\\&t") == TRUE ~ "ATandT",
                                str_detect(owners,"disney") == TRUE ~ "Disney",
                                str_detect(owners,"nintendo") == TRUE~"Nintendo",
                                str_detect(owners,"hitotsubashi") == TRUE~"Hitotubashi",
                                TRUE ~ "Others")
         ) %>% 
  select(owners,new_owners)
```








```{r}
media_franchises %>% 
  mutate(owners = str_to_lower(owners)) %>% 

  mutate(new_owners = case_when(str_detect(owners,"at\\&t") == TRUE ~ "ATandT",
                                str_detect(owners,"disney") == TRUE ~ "Disney",
                                str_detect(owners,"nintendo") == TRUE~"Nintendo",
                                str_detect(owners,"hitotsubashi") == TRUE~"Hitotubashi",
                                
                                str_detect(owners,"square") == TRUE~"SQEX",                                
                                str_detect(owners,"viacom") == TRUE~"viacom",
                                str_detect(owners,"capcom") == TRUE~"capcom",
                                str_detect(owners,"aniplex") == TRUE~"aniplex",
                                str_detect(owners,"sanrio") == TRUE~"sanrio",
                                str_detect(owners,"comcast") == TRUE~"comcast",
                                str_detect(owners,"bandai") == TRUE~"bandai namco holdings",

                                TRUE ~ "Others")
         ) %>% 
  select(owners,new_owners)
```




```{r}
unique(media_franchises$original_media)
```




```{r}
media_franchises %>% 
  filter(original_media %in% c("Cartoon character","Cartoon","Animated cartoon"))
```








```{r}
media_franchises %>% 
  mutate(original_media = factor(original_media)) %>% 
  
  mutate(new_original_media = fct_collapse(original_media,
                                       read_media = c("Novel","Greeting card","Manga","Comic book","Comic strip","Book"),
                                       watch_media = c("Animated series","Animated film","Film" ,"Television series","Anime","Animated cartoon"),
                                       play_media = c("Video game","Visual novel"),
                                       other = c("Digital pet","Cartoon character","Cartoon","Musical theatre")
                                       )
         ) %>% 
  select(original_media,new_original_media)

```

















```{r}

my_label_media_franchises <- media_franchises %>% 

  mutate(owners = str_to_lower(owners)) %>% 
  mutate(new_owners = case_when(str_detect(owners,"at\\&t") == TRUE ~ "ATandT",
                                str_detect(owners,"disney") == TRUE ~ "Disney",
                                str_detect(owners,"nintendo") == TRUE~"Nintendo",
                                str_detect(owners,"hitotsubashi") == TRUE~"Hitotubashi",
                                
                                str_detect(owners,"square") == TRUE~"SQEX",                                
                                str_detect(owners,"viacom") == TRUE~"viacom",
                                str_detect(owners,"capcom") == TRUE~"capcom",
                                str_detect(owners,"aniplex") == TRUE~"aniplex",
                                str_detect(owners,"sanrio") == TRUE~"sanrio",
                                str_detect(owners,"comcast") == TRUE~"comcast",
                                str_detect(owners,"bandai") == TRUE~"bandai namco holdings",

                                TRUE ~ "Others")
         ) %>% 
         
           mutate(original_media = factor(original_media)) %>% 
  
  mutate(new_original_media = fct_collapse(original_media,
                                       read_media = c("Novel","Greeting card","Manga","Comic book","Comic strip","Book"),
                                       watch_media = c("Animated series","Animated film","Film" ,"Television series","Anime","Animated cartoon"),
                                       play_media = c("Video game","Visual novel"),
                                       other = c("Digital pet","Cartoon character","Cartoon","Musical theatre")
                                       )
         ) %>% 
         
         
         select(revenue_category,new_owners,new_original_media,franchise,revenue)
```



```{r}
my_label_media_franchises
```







```{r}
my_label_media_franchises_sum <- 
  my_label_media_franchises %>% 
  group_by(revenue_category,new_owners,new_original_media,franchise) %>% 
  summarise(sum_revenue=sum(revenue)) %>% 
  select(new_original_media,revenue_category,new_owners,franchise,sum_revenue)
```





```{r}
library(alluvial)
```






```{r}

  alluvial(my_label_media_franchises_sum %>% select(-sum_revenue),
         
         freq=my_label_media_franchises_sum$sum_revenue,
         col = as.integer(as.factor(my_label_media_franchises_sum$new_original_media)),
         border = as.factor(my_label_media_franchises_sum$new_original_media),
         hide = my_label_media_franchises_sum$sum_revenue == 0,
         cex = 0.7
)

```






```{r}
my_label_media_franchises_sum <- my_label_media_franchises %>% 
  group_by(revenue_category,new_owners,new_original_media) %>% 
  summarise(sum_revenue=sum(revenue)) %>% 
    select(new_original_media,revenue_category,new_owners,sum_revenue)

```





```{r}

  alluvial(my_label_media_franchises_sum %>% select(-sum_revenue),
           freq=my_label_media_franchises_sum$sum_revenue,
         col = as.integer(as.factor(my_label_media_franchises_sum$new_original_media)),
         border = as.factor(my_label_media_franchises_sum$new_original_media),
         hide = my_label_media_franchises_sum$sum_revenue == 0,
         cex = 0.7
)

```




```{r}
#install.packages("ggalluvial")

library(ggalluvial)

my_label_media_franchises_sum %>% 
ggplot(aes(y=sum_revenue,axis1=new_original_media,axis2=new_owners,axis3=revenue_category))+
  geom_alluvium(aes(fill = new_original_media),width = 0, knot.pos = 1/5, reverse = FALSE)+
  guides(fill	=	FALSE)+
  geom_stratum(width = 1/8, reverse = FALSE)+
  geom_text(stat="stratum",aes(label = after_stat(stratum)),reverse = FALSE)+
  scale_x_continuous(breaks = 1:3, labels = c("new_original_media", "new_owners", "revenue_category"))+
  ggtitle("thanks! ggalluvial!")
```














```{r}
#install.packages("treemap")
library(treemap)
```






```{r}
p <- treemap(my_label_media_franchises_sum,
            index=my_label_media_franchises_sum %>% select(-sum_revenue) %>% names(),
        
            vSize="sum_revenue",
            type="index",
            palette = "Set2",
            #bg.labels=c("white"),
            align.labels=list(
              c("center", "center"), 
              c("right", "bottom")
            )  
          )   
```



```{r}
library(d3treeR)
```






```{r}
d3tree2( p ,  rootname = "all_data" )
```






```{r}
#install.packages("treemapify")
library(treemapify)

my_label_media_franchises_sum %>% 
ggplot(aes(area = sum_revenue, 
           fill = new_owners, 
           label = revenue_category)) +
  geom_treemap() +
  geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                    grow = TRUE)

```



```{r}
my_label_media_franchises_sum %>% 
ggplot(aes(area = sum_revenue, 
           fill = revenue_category, 
           label = new_owners,
           subgroup = new_original_media)) +
  geom_treemap() +
  geom_treemap_subgroup_border()+
  geom_treemap_subgroup_text(color="black")+
  geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                    grow = TRUE)

```
































































```{r}

library(plotly)

fig <- plot_ly(
  type="treemap",
  labels=c("Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"),
  parents=c("", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve")
)
fig

```














```{r}
p <- iris %>% 
  ggplot(aes(x=Sepal.Length,y=Sepal.Width,color=as.factor(Species)))+
  geom_point()

p
```

```{r}
library(plotly)

ggplotly(p)
```















```{r}
media_franchises %>% 
  filter(str_detect(owners,"Type-Moon"))
```



